## Get true colors in tmux
# set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
# Needs this line also to override the default color
set -ga terminal-overrides ",*-256color:Tc"

# Neovim recommends
set-option -g focus-events on
set-option -sg escape-time 10

set -g mouse on
set -g set-clipboard on

## Rebind Prefix
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

## Tmux Control 
bind-key r source-file ~/.config/tmux/tmux.conf
bind-key Q confirm-before -p "Exit terminal? (y/n)" detach-client

## Set VI mode for copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind-key -n M-\; command-prompt

## Appearance
set-option -g status-style bg=default,fg=blue

## Windows
set -g base-index 1
bind-key -n M-v split-window -h -c "#{pane_current_path}"
bind-key -n M-s split-window -c "#{pane_current_path}"
bind-key -n M-n new-window -c "#{pane_current_path}"

## Navigate Window 
bind-key -n M-1 select-window -t :=1
bind-key -n M-2 select-window -t :=2
bind-key -n M-3 select-window -t :=3
bind-key -n M-4 select-window -t :=4
bind-key -n M-5 select-window -t :=5
bind-key -n M-6 select-window -t :=6
bind-key -n M-7 select-window -t :=7
bind-key -n M-8 select-window -t :=8
bind-key -n M-9 select-window -t :=9

## Navigate Panes
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
bind-key -n 'C-p' if-shell "$is_vim" 'send-keys C-p' 'select-pane -l'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-p' select-pane -l

## Rebind clear terminal behind prefix
bind-key C-l send-key 'C-l'

## Resize Panes
bind-key -n M-H resize-pane -L 2
bind-key -n M-J resize-pane -D 2
bind-key -n M-K resize-pane -U 2
bind-key -n M-L resize-pane -R 2

## Renumber windows to the left
bind-key -n M-m movew -r
