[shell]
args = ["-c", "tmux attach || tmux"]
program = "/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#fbf1c7"
text = "CellBackground"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
bright_foreground = "#fbf1c7"
dim_foreground = "#a89984"
foreground = "#ebdbb2"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Ubuntu Mono Nerd Font"

[font.bold_italic]
family = "ubuntu Mono Nerd Font"

[font.italic]
family = "Ubuntu Mono Nerd Font"

[font.normal]
family = "Ubuntu Mono Nerd Font"

# [schemes.everforest_dark_hard.bright]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_hard.normal]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_hard.primary]
# background = "#2b3339"
# foreground = "#d3c6aa"
# 
# [schemes.everforest_dark_medium.bright]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_medium.normal]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_medium.primary]
# background = "#2f383e"
# foreground = "#d3c6aa"
# 
# [schemes.everforest_dark_soft.bright]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_soft.normal]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
# 
# [schemes.everforest_dark_soft.primary]
# background = "#323d43"
# foreground = "#d3c6aa"
# 
# [schemes.everforest_light_hard.bright]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_hard.normal]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_hard.primary]
# background = "#fff9e8"
# foreground = "#5c6a72"
# 
# [schemes.everforest_light_medium.bright]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_medium.normal]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_medium.primary]
# background = "#fdf6e3"
# foreground = "#5c6a72"
# 
# [schemes.everforest_light_soft.bright]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_soft.normal]
# black = "#5c6a72"
# blue = "#3a94c5"
# cyan = "#35a77c"
# green = "#8da101"
# magenta = "#df69ba"
# red = "#f85552"
# white = "#dfddc8"
# yellow = "#dfa000"
# 
# [schemes.everforest_light_soft.primary]
# background = "#f8f0dc"
# foreground = "#5c6a72"
# 
# [schemes.my_gruvbox_dark_hard.bright]
# black = "#928374"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#ebdbb2"
# yellow = "#fabd2f"
# 
# [schemes.my_gruvbox_dark_hard.cursor]
# cursor = "#fbf1c7"
# text = "CellBackground"
# 
# [schemes.my_gruvbox_dark_hard.normal]
# black = "#1d2021"
# blue = "#458588"
# cyan = "#689d6a"
# green = "#98971a"
# magenta = "#b16286"
# red = "#cc241d"
# white = "#a89984"
# yellow = "#d79921"
# 
# [schemes.my_gruvbox_dark_hard.primary]
# background = "#1d2021"
# bright_foreground = "#fbf1c7"
# dim_foreground = "#a89984"
# foreground = "#ebdbb2"
# 
# [schemes.my_gruvbox_dark_hard.selection]
# background = "CellForeground"
# text = "CellBackground"

